### ISSUE TITLE
Newbie advice

### ISSUE THREAD

**Issue by rhcooke** [Hyrules/WinHue3#10]
Hi I have just installed WinHue3 and am having a look at the rules. I have configured the daylight sensor with my longitude and latitude. 
I want to switch on my hall light at sunset,+30 by the default. What value and operator do i use in the rule
/sensors/1/state/daylight gt? 1?

**Comment by Hyrules** [comment]
you need to use the dx operator for the lastupdated property and true or false for the on property depending on what you want take a look a this link : http://stackoverflow.com/questions/26782957/how-to-use-sunset-and-sunrise-data to help you set up your sensor. In your case daylight would be false because you want to turn on the light 30 minutes after sunset.
