### ISSUE TITLE
Dimmer Setup

### ISSUE THREAD

**Issue by AZ-Geek** [Hyrules/WinHue3#128]
I need help setting up 2 dimmer switches. Can you guide me to set up the dimmers with the groupings and lights below? Specifically I do not understand how to set up a single dimmer to control two different rooms without cycling through the lights of the other room on the same switch. Mostly interested in setting up on, off, and brightness levels.

Dimmer1
Living Room (Light1, Light2)
Kitchen (ColorStrip1)

Dimmer2
Bedroom (Light3)
Family Room (Iris1)

Optional on Dimmer1
Office (Light4)

**Comment by Hyrules** [comment]
Just a side note... you won't be able to setup the dimmer with WinHue at this point at least with the rule creator. There is a bug that prevent users from selecting specific state and config of sensors.

I'm not an expert in the field of the dimmer. All I can tell is that you need 2 things to make it work.

First you need to select lastupdated and set it to dx (for changed)
and buttonevent to one of the following : 

Button | Action | Dimmer Button
1000 | INITIAL_PRESS | Button 1 (ON)
1001 | HOLD
1002 | SHORT_RELEASED
1003 | LONG_RELEASED
2000 | INITIAL_PRESS | Button 2 (DIM UP)
2001 | HOLD
2002 | SHORT_RELEASED
2003 | LONG_RELEASED
3000 | INITIAL_PRESS | Button 3 (DIM DOWN)
3001 | HOLD
3002 | SHORT_RELEASED
3003 | LONG_RELEASED
4000 | INITIAL_PRESS | Button 4 (OFF)
4001 | HOLD
4002 | SHORT_RELEASED
4003 | LONG_RELEASED

You would also need to work with groups in order to have your lights for together when you have more than one light. Basically you will need to setup 2 different press for each button you want to setup an event. You can use the short and long release for on and off actions.
