### ISSUE TITLE
cant detect bridge

### ISSUE THREAD

**Issue by sheetzdw** [Hyrules/WinHue3#178]
I have an Amazon Echo plus with 4 Phillips HUE devices. After downloading WinHUE I can not connect to the bridge? Any suggestions?

**Comment by Hyrules** [comment]
Do you have a philips hue bridge ? I'mn not even sure it's possible to have hue devices without the bridge but if this is the case it won't work if you don't have a bridge.

**Comment by Hyrules** [comment]
Most likely the Amazon echo is a special implementation that can control philips hue object. WinHue requires a philips hue bridge otherwise it won't work. Since it does not find the amazon echo it seem that it does not act as a philips hue bridge and might not be remotely controlled. I don't have an amazon echo so I cannot try to make this work if ever possible.

**Comment by sheetzdw** [comment]
OK thanks I will order a hue bridge and work with it , I want to automate my whole home eventually, especially my home theater :)
