### ISSUE TITLE
Auto-Refresh on Scene change 

### ISSUE THREAD

**Issue by fiveseven808** [Hyrules/WinHue3#4]
If you double click and activate a scene, you still need to hit the "Refresh View" Button to see the change that was made/ what the status of the lights you turned on were. 

Could you pull a refresh when the scene command is sent? I noticed the lights affected by the scene become "green" highlighted however their picture status in Winhue GUI is not reflected (i.e. they still show as "off" even though their color and brightness attributes appear to have changed).

**Comment by Hyrules** [comment]
I know that is currently a problem but last time I tested this it didn't work as expected because the bridge does not reflect the changes right away. It takes about 5 to 10 secondes for the properties of a light to refresh after applying a scene. A while ago I had implemented some sort of heartbeat that would pool the bridge every 3 seconds and refresh the states but at one point I changed to the mvvm model and did not reimplement it again. It's the only way I can implement this,

**Comment by fiveseven808** [comment]
Instead of polling, if you know the properties of the scene and what lights are reachable at the time, wouldn't you be able to just set the values statically without pulling a refresh?

**Comment by Hyrules** [comment]
that's the problem. I don't know the properties of the scenes. The scenes objects only gives me the lights which are affected by the scenes. I have to fetch the settings of the scenes from then lights if it's a new scene v2. The only other option is to wait see if the scenes was applied successfully and the change the property of the object in memory with the changed value.

**Comment by fiveseven808** [comment]
When I click on "edit" a scene, it looks like the properties of the scene are pulled, no? When a scene is activated, maybe the scene info can be pulled and then applied to the light statuses when activated? Or the properties of the scenes can be pulled when the program is opened from the beginning?

**Comment by Hyrules** [comment]
I'll see what I can do about this.

**Comment by Hyrules** [comment]
By the way if you test this you will find that only V2 of the scenes refresh right away. (in the bridge that is) Version 1 don't because the informations of lights are not on the bridge so it takes a few seconds for the bridge to pool the light and get it state. That's not the case with V2.

**Comment by fiveseven808** [comment]
Everything seems to be working! Thanks! 

What's the difference between V2 and V1 scenes? I've noticed I only have V2 scenes in my bridge.

**Comment by Hyrules** [comment]
V2 of the scenes settings are stored on the bridge directly. Version 1 had the bridge send the lights their settings for the scene. The bridge didn't know what the color of the light until it was polled so it took a couple of seconds for the bridge to get the new state of the light since it poll them at regular interval. With version 2 that's not the case. The light settings are immediately changed upon activation of a scene.

**Comment by fiveseven808** [comment]
Good to know! Thanks!
