### ISSUE TITLE
Running Winhue without admin privileges?

### ISSUE THREAD

**Issue by sicherist** [Hyrules/WinHue3#48]
Hello,

ist it possible to run Winhue without UAC asking for the admin password? Or in other words: Why does Winhue need admin privileges anyway?

Kind Regards!

**Comment by Hyrules** [comment]
At the moment not possible. WinHue needs admin privileges to write on the disk to save settings and to send command through the network card. I have no clue on how to do this without the admin if ever possible.

**Comment by sicherist** [comment]
Thank you for your reply. I have no knowledge about programming so please excuse me if I might be missing something, but a lot of programs write to the disk and access the network without admin privileges. Browsers for example. As far as I know, the writing to disk part could be solved by writing to a subfolder in %appdata% instead of the installation directory in 'Program Files'. I have no idea about the networking aspect though.

**Comment by Hyrules** [comment]
Yes I know those. The problem is that I don't know how to do it with WinHue. By default the app request admin privileges. Everytime I tried to find how to do it lately I wasnt able to get the info I was looking. If there is way to do this I will certainly do it. I will have to do more intensive research on the subject.

**Comment by Hyrules** [comment]
Good news for you I just got a breakthrough in this matter and next version of WinHue should be able to run without admin.
