### ISSUE TITLE
whc not recognizing that bridge is paired

### ISSUE THREAD

**Issue by elspencer-2323** [Hyrules/WinHue3#58]
Hello sir, thanks for your efforts on this program. I've just installed beta 24, and got my bridge paired in the GUI, and all the scenes and lights are visible and working fine. I would like to use the command line for scripting but every time I try to pull any info from whc it tells me "Please pair at least one bridge with WinHue in order to use whc." 

I see that there was some issue with the location of the settings file - it is in appdata roaming and nowhere else - do I need to move the settings file elsewhere for whc to notice it?

Many thanks. es

**Comment by Hyrules** [comment]
There is a bug in latest beta the make whc look at the wrong place for the WinHue settings file. If you want to fix this quickly go to appdata folder in your profile and the the WinHue folder and copy the Winhue settings file to your documents / WinHue folder.  Otherwise you can use this version of whc has it should be fixed.

[whc.zip](https://github.com/Hyrules/WinHue3/files/705356/whc.zip)

**Comment by elspencer-2323** [comment]
The updated file you posted did work, thanks very much. I noticed that Winhue did not create a folder for itself in the Documents folder. I had tried creating this folder manually and moving the settings file to it but that did not work.

**Comment by Hyrules** [comment]
Latest version uses %APPDATA%\WinHue3 as a folder to store the settings file. With the updated whc you don't need the WinHue folder in my documents. It will use the appdata one.
