### ISSUE TITLE
Keeps crashing. Especially when running and brought out of sleep mode 

### ISSUE THREAD

**Issue by fiveseven808** [Hyrules/WinHue3#9]
[log 2016-07-19.zip](https://github.com/Hyrules/WinHue3/files/372775/log.2016-07-19.zip)

Doesn't crash every time the computer is brought out of sleep, however that's when I notice that it's crashed the most often. Not sure how to go about testing this.

**Comment by Hyrules** [comment]
This is most likely normal. When the computer is sent in sleep mode event the network adapter does not work so the program cannot get the state of the light. It will crash at wake up because it is not getting an answer from the bridge. I will try to fix this condition.

**Comment by fiveseven808** [comment]
Any update to this yet by any chance? Thanks!

**Comment by Hyrules** [comment]
Sorry no. I'm on vacation right now and i'm not doing any kind of programming. I will take a look at this when I get back after the 15th of august.

**Comment by fiveseven808** [comment]
No worries! Have a great vacation! :+1:

**Comment by Hyrules** [comment]
I have started to program again. This might take a while before I release a new version because I want to rewrite HueLib which is the library I use to communicate with the bridge. I want to simplify things a little and try to make it null proof. Making it null proof will remove almost all exception from the program. I'm also removing the plugins function of the program since nobody seems to be using it except me. So I will integrate the already existing plugins in and add more functions that way.

**Comment by Hyrules** [comment]
Good thing is this is now fixed. Problem now is that the app crawls when the bridge does not respond. I have to implement some kind of async threading. I'll have a new version to test soon.

**Comment by Hyrules** [comment]
Here you can try this version and let me know if it works properly.

[WinHue 3 BETA 18 Setup.zip](https://github.com/Hyrules/WinHue3/files/479018/WinHue.3.BETA.18.Setup.zip)

**Comment by Hyrules** [comment]
Great thanks alot. @fiveseven808 does this fix it for you ? I will close the issue if it's the case.
